### PR TITLE
Completed iBus Implementation

### PR DESCRIPTION
**Pull request by thementat**

### CODE REVIEW

**Comment by Quick-Flash** [comment]
any reason why this was closed?

**Comment by thementat** [comment]
Hey!  I’m kinda clueless with Github, and I thought I was pull-requesting my fork.  I’ve gotten it working though, and you are more than welcome to include it.  Let me know how to best do that!

From: Kevin Plaizier ***@***.***>
Date: Monday, May 17, 2021 at 2:47 PM
To: nickrehm/dRehmFlight ***@***.***>
Cc: Chris Bradley ***@***.***>, State change ***@***.***>
Subject: Re: [nickrehm/dRehmFlight] Completed iBus Implementation (#2)

any reason why this was closed?

**Comment by nickrehm** [comment]
I'll be pushing out a major update this summer and would love to include your ibus implementation. What's the best way to credit you?

**Comment by thementat** [comment]
However you see fit… FWIW, I didn’t develop the framework, I just provided some glue!

Thanks for providing this flight controller BTW!  I just maidened my bicopter yesterday (or rather stuffed it into my back lawn), and it’s been a fun project so far!

From: nickrehm ***@***.***>
Date: Monday, May 17, 2021 at 6:20 PM
To: nickrehm/dRehmFlight ***@***.***>
Cc: Chris Bradley ***@***.***>, State change ***@***.***>
Subject: Re: [nickrehm/dRehmFlight] Completed iBus Implementation (#2)

I'll be pushing out a major update this summer and would love to include your ibus implementation. What's the best way to credit you?

**Comment by Quick-Flash** [comment]
> I'll be pushing out a major update this summer and would love to include your ibus implementation. What's the best way to credit you?

@nickrehm I think that this project could be very helpful for use as an educational device. I'm really thinking that getting students to build a vtol using your software would be an incredible learning tool for them. For that reason I would love to help somewhat with this project. I've already spent hundreds of hours writing code for drone applications, and I have some suggestions and ways I could help contribute here. Just let me know.

**Pull request closed without merging**
